using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace MedPersistance.AutoGenerated
{
    public partial class MedContext : DbContext
    {
        public MedContext()
        {
        }

        public MedContext(DbContextOptions<MedContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Address> Addresses { get; set; } = null!;
        public virtual DbSet<Department> Departments { get; set; } = null!;
        public virtual DbSet<Diagnose> Diagnoses { get; set; } = null!;
        public virtual DbSet<Doctor> Doctors { get; set; } = null!;
        public virtual DbSet<DoctorInfo> DoctorInfos { get; set; } = null!;
        public virtual DbSet<DoctorPlace> DoctorPlaces { get; set; } = null!;
        public virtual DbSet<Examination> Examinations { get; set; } = null!;
        public virtual DbSet<Gender> Genders { get; set; } = null!;
        public virtual DbSet<Role> Languages { get; set; } = null!;
        public virtual DbSet<Medicine> Medicines { get; set; } = null!;
        public virtual DbSet<Oblast> Oblasts { get; set; } = null!;
        public virtual DbSet<Organization> Organizations { get; set; } = null!;
        public virtual DbSet<Patient> Patients { get; set; } = null!;
        public virtual DbSet<Payment> Payments { get; set; } = null!;
        public virtual DbSet<PaymentHystory> PaymentHystories { get; set; } = null!;
        public virtual DbSet<PlasticCard> PlasticCards { get; set; } = null!;
        public virtual DbSet<Region> Regions { get; set; } = null!;
        public virtual DbSet<Role> Roles { get; set; } = null!;
        public virtual DbSet<Roletype> Roletypes { get; set; } = null!;
        public virtual DbSet<Status> Statuses { get; set; } = null!;
        public virtual DbSet<UserModule> UserModules { get; set; } = null!;
        public virtual DbSet<WeekDay> WeekDays { get; set; } = null!;
        public virtual DbSet<WorkingHour> WorkingHours { get; set; } = null!;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseNpgsql("Server=localhost;Database=Med;Username=postgres;Password=postgres;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Address>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");

                entity.HasOne(d => d.Oblast)
                    .WithMany(p => p.Addresses)
                    .HasForeignKey(d => d.OblastId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("address_oblast_id_fkey");

                entity.HasOne(d => d.Region)
                    .WithMany(p => p.Addresses)
                    .HasForeignKey(d => d.RegionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("address_region_id_fkey");
            });

            modelBuilder.Entity<Department>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            });

            modelBuilder.Entity<Diagnose>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");

                entity.HasOne(d => d.Medicine)
                    .WithMany(p => p.Diagnoses)
                    .HasForeignKey(d => d.MedicineId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("diagnose_medicine_id_fkey");
            });

            modelBuilder.Entity<Doctor>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");

                entity.Property(e => e.UserModuleId).ValueGeneratedOnAdd();

                entity.HasOne(d => d.Department)
                    .WithMany(p => p.Doctors)
                    .HasForeignKey(d => d.DepartmentId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("doctor_department_id_fkey");

                entity.HasOne(d => d.DoctorInfo)
                    .WithMany(p => p.Doctors)
                    .HasForeignKey(d => d.DoctorInfoId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("doctor_doctor_info_id_fkey");

                entity.HasOne(d => d.DoctorPlace)
                    .WithMany(p => p.Doctors)
                    .HasForeignKey(d => d.DoctorPlaceId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("doctor_doctor_place_id_fkey");

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.Doctors)
                    .HasForeignKey(d => d.PatientId)
                    .HasConstraintName("doctor_patient_id_fkey");

                entity.HasOne(d => d.UserModule)
                    .WithMany(p => p.Doctors)
                    .HasForeignKey(d => d.UserModuleId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("doctor_user_module_id_fkey");
            });

            modelBuilder.Entity<DoctorInfo>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");

                entity.HasOne(d => d.DoctorPlace)
                    .WithMany(p => p.DoctorInfos)
                    .HasForeignKey(d => d.DoctorPlaceId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("doctor_info_doctor_place_id_fkey");

                entity.HasOne(d => d.WorkingHours)
                    .WithMany(p => p.DoctorInfos)
                    .HasForeignKey(d => d.WorkingHoursId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("doctor_info_working_hours_id_fkey");
            });

            modelBuilder.Entity<DoctorPlace>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            });

            modelBuilder.Entity<Examination>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            });

            modelBuilder.Entity<Gender>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            });

            modelBuilder.Entity<Role>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            });

            modelBuilder.Entity<Medicine>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            });

            modelBuilder.Entity<Oblast>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            });

            modelBuilder.Entity<Organization>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");

                entity.HasOne(d => d.Oblast)
                    .WithMany(p => p.Organizations)
                    .HasForeignKey(d => d.OblastId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("organization_oblast_id_fkey");

                entity.HasOne(d => d.Region)
                    .WithMany(p => p.Organizations)
                    .HasForeignKey(d => d.RegionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("organization_region_id_fkey");
            });

            modelBuilder.Entity<Patient>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");

                entity.Property(e => e.UserModuleId).ValueGeneratedOnAdd();

                entity.HasOne(d => d.Address)
                    .WithMany(p => p.Patients)
                    .HasForeignKey(d => d.AddressId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("patient_address_id_fkey");

                entity.HasOne(d => d.Diagnose)
                    .WithMany(p => p.Patients)
                    .HasForeignKey(d => d.DiagnoseId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("patient_diagnose_id_fkey");

                entity.HasOne(d => d.Examination)
                    .WithMany(p => p.Patients)
                    .HasForeignKey(d => d.ExaminationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("patient_examination_id_fkey");

                entity.HasOne(d => d.Organization)
                    .WithMany(p => p.Patients)
                    .HasForeignKey(d => d.OrganizationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("patient_organization_id_fkey");

                entity.HasOne(d => d.Payment)
                    .WithMany(p => p.Patients)
                    .HasForeignKey(d => d.PaymentId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("patient_payment_id_fkey");

                entity.HasOne(d => d.UserModule)
                    .WithMany(p => p.Patients)
                    .HasForeignKey(d => d.UserModuleId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("patient_user_module_id_fkey");
            });

            modelBuilder.Entity<Payment>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");

                entity.HasOne(d => d.PaymentHystoryNavigation)
                    .WithMany(p => p.Payments)
                    .HasForeignKey(d => d.PaymentHystory)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("payment_payment_hystory_fkey");

                entity.HasOne(d => d.PlasticCard)
                    .WithMany(p => p.Payments)
                    .HasForeignKey(d => d.PlasticCardId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("payment_plastic_card_id_fkey");
            });

            modelBuilder.Entity<PaymentHystory>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");

                entity.HasOne(d => d.RecievedCard)
                    .WithMany(p => p.PaymentHystoryRecievedCards)
                    .HasForeignKey(d => d.RecievedCardId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("payment_hystory_recieved_card_id_fkey");

                entity.HasOne(d => d.SentCard)
                    .WithMany(p => p.PaymentHystorySentCards)
                    .HasForeignKey(d => d.SentCardId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("payment_hystory_sent_card_id_fkey");
            });

            modelBuilder.Entity<PlasticCard>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            });

            modelBuilder.Entity<Region>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");

                entity.HasOne(d => d.Oblast)
                    .WithMany(p => p.Regions)
                    .HasForeignKey(d => d.OblastId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("region_oblast_id_fkey");
            });

            modelBuilder.Entity<Role>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");

                entity.HasOne(d => d.Roletype)
                    .WithMany(p => p.Roles)
                    .HasForeignKey(d => d.RoletypeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("role_roletype_id_fkey");
            });

            modelBuilder.Entity<Roletype>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            });

            modelBuilder.Entity<Status>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            });

            modelBuilder.Entity<UserModule>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");

                entity.HasOne(d => d.Gender)
                    .WithMany(p => p.UserModules)
                    .HasForeignKey(d => d.GenderId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("user_module_gender_id_fkey");

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.UserModules)
                    .HasForeignKey(d => d.LanguageId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("user_module_language_id_fkey");

                entity.HasOne(d => d.Oblast)
                    .WithMany(p => p.UserModules)
                    .HasForeignKey(d => d.OblastId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("user_module_oblast_id_fkey");

                entity.HasOne(d => d.Organization)
                    .WithMany(p => p.UserModules)
                    .HasForeignKey(d => d.OrganizationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("user_module_organization_id_fkey");

                entity.HasOne(d => d.Region)
                    .WithMany(p => p.UserModules)
                    .HasForeignKey(d => d.RegionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("user_module_region_id_fkey");

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.UserModules)
                    .HasForeignKey(d => d.RoleId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("user_module_role_id_fkey");

                entity.HasOne(d => d.Status)
                    .WithMany(p => p.UserModules)
                    .HasForeignKey(d => d.StatusId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("user_module_status_id_fkey");
            });

            modelBuilder.Entity<WeekDay>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            });

            modelBuilder.Entity<WorkingHour>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasDefaultValueSql("CURRENT_TIMESTAMP");

                entity.HasOne(d => d.WeekDay)
                    .WithMany(p => p.WorkingHours)
                    .HasForeignKey(d => d.WeekDayId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("working_hours_week_day_id_fkey");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
