using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MedPersistance.AutoGenerated
{
    [Table("role")]
    public partial class Role
    {
        public Role()
        {
            UserModules = new HashSet<UserModule>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("name")]
        [StringLength(100)]
        public string Name { get; set; } = null!;
        [Column("roletype_id")]
        public int RoletypeId { get; set; }
        [Column("created_date", TypeName = "timestamp without time zone")]
        public DateTime CreatedDate { get; set; }
        [Column("created_user_id")]
        public int? CreatedUserId { get; set; }
        [Column("modified_date", TypeName = "timestamp without time zone")]
        public DateTime? ModifiedDate { get; set; }
        [Column("modified_user_id")]
        public int? ModifiedUserId { get; set; }

        [ForeignKey(nameof(RoletypeId))]
        [InverseProperty("Roles")]
        public virtual Roletype Roletype { get; set; } = null!;
        [InverseProperty(nameof(UserModule.Role))]
        public virtual ICollection<UserModule> UserModules { get; set; }
    }
}
